import Navbar from "@/component/Navbar";
import ProfileSideBar from "@/component/Sidebar/ProfileSideBar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./tailwind.css";
import Footer from "@/component/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-homeBg dark:bg-homeTwoBg-dark min-h-screen bg-no-repeat bg-center bg-cover bg-fixed md:pb-16 w-full ${geistSans.variable} ${geistMono.variable} antialiased `}>
        <div className="flex mt-24 justify-between px-[10rem]">
          {/* Side bar*/}
          <ProfileSideBar />
          <div className="col-span-12 lg:col-span-8">
            <Navbar />
            <div className="bg-white w-[50vw] border-2 border-gray-50 shadow-md rounded-xl">
              {children}
              <Footer />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
